baseURL = "https://kudarizakawonobore.github.io/techblog/"
languageCode = "ja"
title = "下り坂を昇るブログ"

theme = "ananke"

publishDir = "docs"
canonifyurls = true

[params]
time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"
# Sections to publish in the main RSS feed.
rss_sections = ["blog"]