baseURL = "https://kudarizakawonobore.github.io/techblog/"
languageCode = "ja"
title = "下り坂を昇るブログ"

theme = "ananke"

publishDir = "docs"
canonifyurls = true

summaryLength = 7

[menu]
[[menu.main]]
identifier = "Posts"
name = "Posts"
url = "/blog/"

[[menu.main]]
identifier = "Contact"
name = "Contact"
url = "/contact/"

[params]
featured_image = '/images/gohugo-default-sample-hero-image.jpg'
images = ['./images/gohugo-default-sample-hero-image.jpg']